"""
DiCE (Diverse Counterfactual Explanations) — "what would need to change for
this prediction to flip to non-failure?"

Counterfactuals are what-if scenarios generated by searching for nearby,
valid points that the model classifies differently — they are not verified
causal relationships and not guaranteed physical maintenance instructions.
Treat them as hypotheses for a domain expert to evaluate, not as instructions
to act on directly.

To keep suggestions realistic:
  * `permitted_range` bounds every feature to its min/max observed in the
    training data, so DiCE cannot propose values outside the sensor's
    historical operating range.
  * `features_to_vary` defaults to a limited, caller-supplied subset (in
    practice, the top SHAP-ranked features) rather than all selected
    features, so counterfactuals stay sparse and don't suggest changing
    dozens of sensors at once.
  * Returned counterfactuals are sorted by how many features they change, so
    the sparsest (most actionable) alternative is surfaced first.

The "random" search method is used because it works with any scikit-learn
classifier exposing `predict_proba` (including tree ensembles), unlike the
gradient-based method which requires a differentiable model.
"""

from __future__ import annotations

from typing import Any

import dice_ml
import pandas as pd

from src.utils import CLASS_NAMES, RANDOM_SEED, TARGET_COLUMN, get_logger

logger = get_logger(__name__)


class CounterfactualGenerationError(RuntimeError):
    """Raised when DiCE cannot find any valid counterfactual for a query instance."""


class DiCEExplainer:
    def __init__(
        self,
        training_data: pd.DataFrame,
        target: pd.Series,
        model,
        feature_names: list[str] | None = None,
        outcome_name: str = TARGET_COLUMN,
    ):
        self.feature_names = feature_names or list(training_data.columns)
        self.outcome_name = outcome_name
        self.model = model

        df = training_data[self.feature_names].copy()
        df[outcome_name] = target.values

        # Bound each feature to its 1st-99th percentile of observed training
        # values rather than raw min/max: SECOM's sensor features contain
        # occasional extreme outliers, and a raw min/max bound would let a
        # single outlier license an unrealistically large suggested change.
        self.permitted_range = {
            f: [float(df[f].quantile(0.01)), float(df[f].quantile(0.99))] for f in self.feature_names
        }

        self.data_interface = dice_ml.Data(
            dataframe=df,
            continuous_features=self.feature_names,
            outcome_name=outcome_name,
        )
        self.model_interface = dice_ml.Model(model=model, backend="sklearn", model_type="classifier")
        self.dice = dice_ml.Dice(self.data_interface, self.model_interface, method="random")

    def generate_counterfactuals(
        self,
        query_instance: pd.DataFrame,
        total_cfs: int = 3,
        features_to_vary: list[str] | None = None,
        random_state: int = RANDOM_SEED,
    ) -> dict[str, Any]:
        if len(query_instance) != 1:
            raise ValueError("generate_counterfactuals expects a single-row DataFrame.")

        query = query_instance[self.feature_names].astype(float)
        proba_original = float(self.model.predict_proba(query)[0, 1])
        vary = features_to_vary or self.feature_names

        try:
            cf_result = self.dice.generate_counterfactuals(
                query,
                total_CFs=total_cfs,
                desired_class="opposite",
                features_to_vary=vary,
                permitted_range=self.permitted_range,
                random_seed=random_state,
            )
        except Exception as exc:  # dice-ml raises its own exception types on infeasible searches
            logger.warning("DiCE could not generate counterfactuals: %s", exc)
            return {
                "original_probability": proba_original,
                "original_class": CLASS_NAMES[int(proba_original >= 0.5)],
                "counterfactuals": [],
                "error": str(exc),
            }

        cf_df = cf_result.cf_examples_list[0].final_cfs_df
        counterfactuals: list[dict[str, Any]] = []

        if cf_df is not None and len(cf_df) > 0:
            original_row = query.iloc[0]
            for _, cf_row in cf_df.iterrows():
                cf_input = pd.DataFrame([cf_row[self.feature_names].astype(float)], columns=self.feature_names)
                proba_cf = float(self.model.predict_proba(cf_input)[0, 1])

                changes = []
                for f in self.feature_names:
                    original_val = float(original_row[f])
                    new_val = float(cf_row[f])
                    if abs(new_val - original_val) > 1e-6:
                        changes.append(
                            {
                                "feature": f,
                                "original_value": original_val,
                                "counterfactual_value": new_val,
                                "delta": new_val - original_val,
                            }
                        )

                counterfactuals.append(
                    {
                        "failure_probability": proba_cf,
                        "predicted_class": CLASS_NAMES[int(proba_cf >= 0.5)],
                        "n_features_changed": len(changes),
                        "changes": changes,
                    }
                )
            counterfactuals.sort(key=lambda c: c["n_features_changed"])

        return {
            "original_probability": proba_original,
            "original_class": CLASS_NAMES[int(proba_original >= 0.5)],
            "counterfactuals": counterfactuals,
        }

    def explain_counterfactual_text(self, result: dict[str, Any], cf_index: int = 0) -> str:
        lines = [
            "Current prediction:",
            f"{result['original_class']} — {result['original_probability']:.0%}",
            "",
        ]
        if not result["counterfactuals"]:
            lines.append("No realistic counterfactual was found within the permitted feature ranges.")
            return "\n".join(lines)

        cf = result["counterfactuals"][cf_index]
        lines += [
            "Counterfactual:",
            f"{cf['predicted_class']} — {cf['failure_probability']:.0%}",
            "",
            "Changes suggested:",
        ]
        for change in cf["changes"]:
            lines.append(
                f"{change['feature']}: {change['original_value']:.3f} -> {change['counterfactual_value']:.3f}"
            )
        lines += [
            "",
            "Note: this is a what-if scenario produced by searching for nearby inputs the model "
            "would classify differently. It is not a guaranteed or physically validated maintenance "
            "instruction — changes should be reviewed by a domain expert before acting on them.",
        ]
        return "\n".join(lines)
